# Generated by Django 4.2.1 on 2023-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bids_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='current_price',
        ),
        migrations.AddField(
            model_name='bids',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='listings',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
