# Generated by Django 4.2.1 on 2023-09-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bids_current_price_bids_new_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
