# Generated by Django 4.2.1 on 2023-09-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listings_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='starting_bid',
        ),
    ]
