# Generated by Django 4.2.1 on 2023-09-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listings_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(default='All', max_length=100),
        ),
    ]
