# Generated by Django 4.2.1 on 2023-09-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
    ]
